export const locationSuggestions = [
  'Connaught Place', 'Karol Bagh', 'Chandni Chowk', 'Rajouri Garden', 'Dwarka Sector 21',
  'Saket', 'Hauz Khas', 'Greater Kailash', 'South Extension', 'Vasant Kunj', 'Punjabi Bagh',
  'Janakpuri', 'Lajpat Nagar', 'Okhla', 'Malviya Nagar', 'Sarojini Nagar', 'Green Park',
  'Rohini Sector 3', 'Rohini Sector 7', 'Model Town', 'Pitampura', 'Shahdara', 'Mayur Vihar',
  'Kalkaji', 'Mehrauli', 'Tilak Nagar', 'Ashok Vihar', 'Paharganj', 'Patel Nagar',
  'Lodhi Colony', 'Defence Colony', 'Chanakyapuri', 'Civil Lines', 'Yamuna Vihar', 'Vivek Vihar',
  'Krishna Nagar', 'Mandawali', 'Azadpur', 'Adarsh Nagar', 'Kashmere Gate', 'GTB Nagar',
  'Rajendra Place', 'Inderpuri', 'Moti Nagar', 'Kirti Nagar', 'Najafgarh', 'Palam', 'Uttam Nagar',
  'Shalimar Bagh', 'Sadar Bazaar', 'Bhajanpura', 'Seelampur', 'Dilshad Garden', 'Anand Vihar',
  'IP Extension', 'Preet Vihar', 'Karkardooma', 'Patparganj', 'Nirman Vihar', 'Shakarpur',
  'Dwarka Sector 12', 'Dwarka Sector 9', 'Dwarka Sector 19', 'Dwarka Sector 6', 'Janpath',
  'Barakhamba Road', 'Jangpura', 'Nizamuddin', 'Jamia Nagar', 'Khan Market', 'New Friends Colony',
  'East of Kailash', 'Chirag Delhi', 'Jasola', 'Madanpur Khadar', 'Mahipalpur', 'Vasant Vihar',
  'Dwarka Mor', 'Najafgarh Road', 'Shankar Road', 'Shanti Niketan', 'Katwaria Sarai',
  'Munirka', 'RK Puram', 'Sarita Vihar', 'Govindpuri', 'Tughlakabad', 'Badarpur',
  'Faridabad Road Border', 'Dwarka Sector 10', 'Dwarka Sector 14', 'Dwarka Sector 17',
  'Shivaji Place', 'Paschim Vihar', 'Subhash Nagar', 'Tilak Nagar Market', 'Tagore Garden',
  'Peeragarhi', 'Mundka', 'Nangloi', 'Rajouri Garden Extension', 'Punjabi Bagh Club Road',
  'Inderlok', 'Zakhira', 'Lajwanti Garden', 'Naraina', 'Satya Niketan', 'South Campus',
  'Delhi Cantt', 'Dhaula Kuan', 'Talkatora Road', 'Indira Vihar', 'Kingsway Camp',
  'Hudson Lane', 'Kamla Nagar', 'GT Road Shahdara', 'Maujpur', 'Gokalpuri', 'Karawal Nagar',
  'Burari', 'Sant Nagar', 'Mukherjee Nagar', 'Majnu Ka Tila', 'Timarpur', 'Wazirabad',
  'Yamuna Pushta', 'Shastri Park', 'Seemapuri', 'Jhilmil Colony', 'Vishwas Nagar',
  'Ramprastha', 'Kondli', 'Trilokpuri', 'Kalyanpuri', 'Pandav Nagar', 'Geeta Colony',
  'Gandhi Nagar', 'Ramesh Park', 'Shahdara Flyover', 'Mandoli', 'Nand Nagri', 'Sunder Nagri',
  'GTB Enclave', 'Khajuri Khas', 'Dayalpur', 'Bhalswa Dairy', 'Jahangirpuri', 'Haiderpur',
  'Samaypur Badli', 'Badli', 'Libaspur', 'Azadpur Mandi', 'Majlis Park', 'Adarsh Nagar Metro',
  'Shalimar Bagh Club Road', 'Ashok Vihar Phase 1', 'Ashok Vihar Phase 2', 'Ashok Vihar Phase 3',
  'Ashok Vihar Phase 4', 'Wazirpur Industrial Area', 'Netaji Subhash Place', 'Rani Bagh',
  'Saraswati Vihar', 'Kohat Enclave', 'Prashant Vihar', 'Sector 16 Rohini', 'Sector 18 Rohini',
  'Sector 24 Rohini', 'Sector 25 Rohini', 'Sector 28 Rohini', 'Sector 29 Rohini', 'Sector 32 Rohini'
];
